// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FishingTripInputController from "./fishing_trip_input_controller"
application.register("fishing-trip-input", FishingTripInputController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalhandlerController from "./modalhandler_controller"
application.register("modalhandler", ModalhandlerController)
